### ISSUE TITLE
Change icons on perk cards

### ISSUE THREAD

**Issue by Mikivitkovski** [learnhubmk/app#375] opened 2024-06-18 11:43 UTC
Change icons on perk cards to be same from figma design
https://www.figma.com/design/YLlXQlNrfYbBLOyOoIiEp3/learnhub?node-id=2496-3225&t=K1dkCoiPdR8mLnsA-0

**Comment by davorminchorov** [comment] 2024-06-18 13:05
Isn’t this a duplicate of https://github.com/learnhubmk/app/issues/368?

**Closed** 2024-06-18 13:17 UTC
Labels: frontend
